#:schema node_modules/wrangler/config-schema.json
name = "api-and-kv-example"
main = "src/index.ts"
compatibility_date = "2024-08-06"

[[kv_namespaces]]
binding = "KV"
id = "45ce0cdcc47947eba9022157f60f6789"
